# Generated by Django 6.0.3 on 2026-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carmel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                ("description", models.TextField(max_length=255)),
                (
                    "price_contribution_default",
                    models.DecimalField(decimal_places=2, max_digits=2),
                ),
                ("pay_day_contribution_default", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
