# Generated by Django 4.2.30 on 2026-07-29 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carmel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=4000)),
                (
                    "price_contribution_default",
                    models.DecimalField(decimal_places=2, max_digits=1000),
                ),
                (
                    "pay_day_contribution_default",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ]
                    ),
                ),
                ("diocese", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name": "Carmelo",
                "verbose_name_plural": "Carmelos",
            },
        ),
    ]
