# Generated by Django 4.2.30 on 2026-08-11 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="price_contribution_default",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Contribuição padrão",
            ),
        ),
    ]
