# Generated by Django 6.0.3 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="pay_day_contribution_default",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="carmel",
            name="price_contribution_default",
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
