# Generated by Django 6.0.3 on 2026-05-28 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmel", "0002_alter_carmel_pay_day_contribution_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="pay_day_contribution_default",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ]
            ),
        ),
    ]
