# Generated by Django 6.0.3 on 2026-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmel", "0003_alter_carmel_pay_day_contribution_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="description",
            field=models.TextField(max_length=4000),
        ),
    ]
