# Generated by Django 4.2.30 on 2026-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0004_alter_carmel_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="carmel",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
