# Generated by Django 4.2.30 on 2026-07-13 20:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0006_alter_carmel_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carmel",
            options={"verbose_name": "Carmelo", "verbose_name_plural": "Carmelos"},
        ),
    ]
