# Generated by Django 4.2.30 on 2026-07-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0007_alter_carmel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmel",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carmel",
            name="diocese",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
