# Generated by Django 4.2.30 on 2026-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0008_carmel_city_carmel_diocese"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="carmel",
            name="diocese",
            field=models.CharField(max_length=255),
        ),
    ]
