# Generated by Django 4.2.30 on 2026-07-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0010_alter_carmel_city_alter_carmel_diocese"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmel",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="carmel",
            name="diocese",
            field=models.CharField(default="", max_length=255),
        ),
    ]
