# Generated by Django 6.0.3 on 2026-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_contribution_unique_member_contribution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="date_pay",
            field=models.DateField(verbose_name="Data do Pagamento"),
        ),
    ]
