# Generated by Django 4.2.30 on 2026-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0003_alter_contribution_date_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
