# Generated by Django 4.2.30 on 2026-07-13 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contributions", "0005_alter_contribution_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membro",
            ),
        ),
    ]
