# Generated by Django 4.2.30 on 2026-07-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0008_carmel_city_carmel_diocese"),
        ("contributions", "0006_alter_contribution_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="carmel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="carmel.carmel",
            ),
        ),
    ]
