# Generated by Django 6.0.3 on 2026-05-12 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=15, verbose_name="Nome do Voto")),
                ("date", models.DateTimeField(verbose_name="Data e Hora do Voto")),
                (
                    "type",
                    models.CharField(
                        choices=[("DEF", "Definitivo"), ("TEMP", "Temporários")],
                        max_length=4,
                        verbose_name="Grau do Voto",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Membro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
            },
        ),
    ]
