# Generated by Django 4.2.30 on 2026-07-29 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VotesRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=255)),
            ],
            options={
                "verbose_name": "Registro do Voto e suas caracteristicas",
                "verbose_name_plural": "Registro dos Votos e suas caracteristicas",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(verbose_name="Data e Hora do Voto")),
                (
                    "type",
                    models.CharField(
                        choices=[("DEF", "Definitivo"), ("TEMP", "Temporários")],
                        max_length=4,
                        verbose_name="Grau do Voto",
                    ),
                ),
                (
                    "year_duration",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Quantos Anos dura esse voto",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Membro",
                    ),
                ),
                (
                    "votes_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="votes.votesregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto do Membro",
                "verbose_name_plural": "Votos do Membro",
            },
        ),
    ]
