# Generated by Django 6.0.3 on 2026-05-16 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotesRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=255)),
                (
                    "year_duration",
                    models.IntegerField(verbose_name="Quantos Anos dura esse voto"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vote",
            name="votes_registration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="votes.votesregistration",
            ),
        ),
    ]
