# Generated by Django 4.2.30 on 2026-08-11 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="year_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Quantos Anos dura esse voto",
            ),
        ),
    ]
