# Generated by Django 6.0.3 on 2026-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0002_votesregistration_vote_votes_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votesregistration",
            name="year_duration",
        ),
        migrations.AddField(
            model_name="vote",
            name="year_duration",
            field=models.IntegerField(
                null=True, verbose_name="Quantos Anos dura esse voto"
            ),
        ),
    ]
