# Generated by Django 6.0.3 on 2026-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0003_remove_votesregistration_year_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={
                "verbose_name": "Voto do Membro",
                "verbose_name_plural": "Votos do Membro",
            },
        ),
        migrations.AlterModelOptions(
            name="votesregistration",
            options={
                "verbose_name": "Registro do Voto e suas caracteristicas",
                "verbose_name_plural": "Registro dos Votos e suas caracteristicas",
            },
        ),
        migrations.RemoveField(
            model_name="vote",
            name="name",
        ),
        migrations.AlterField(
            model_name="vote",
            name="year_duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantos Anos dura esse voto"
            ),
        ),
    ]
