# Generated by Django 4.2.30 on 2026-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0004_alter_vote_options_alter_votesregistration_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="votesregistration",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
