# Generated by Django 4.2.30 on 2026-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0005_alter_vote_id_alter_votesregistration_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="votesregistration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
