# Generated by Django 4.2.30 on 2026-07-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0006_alter_vote_id_alter_votesregistration_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="votes_registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="votes.votesregistration",
            ),
        ),
    ]
