# Generated by Django 6.0.3 on 2026-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordaccess",
            name="expired_at",
            field=models.DateTimeField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Data e Hora de expiração do token",
            ),
        ),
        migrations.AlterField(
            model_name="resetpasswordaccess",
            name="token",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="token de acesso"
            ),
        ),
    ]
