# Generated by Django 4.2.30 on 2026-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_resetpasswordaccess_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordaccess",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
