# Generated by Django 4.2.30 on 2026-07-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_resetpasswordaccess_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordaccess",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
