# Generated by Django 6.0.3 on 2026-05-12 14:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=80, verbose_name="Rua")),
                ("number", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "neighborhood",
                    models.CharField(max_length=50, verbose_name="Bairro"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "zipcode",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=35, verbose_name="Nome do Membro"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "church",
                    models.CharField(
                        max_length=100, verbose_name="Igreja que Participa"
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=datetime.date(2026, 5, 12),
                        verbose_name="Data de Entrada",
                    ),
                ),
                ("carmel", models.CharField(blank=True, default="", max_length=50)),
                (
                    "roles",
                    models.CharField(
                        choices=[
                            ("MN", "Responsavel"),
                            ("FN", "Tesoreiro"),
                            ("NM", "Normal"),
                        ],
                        default="NM",
                        max_length=2,
                        verbose_name="Função no Carmelo",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.address",
                        verbose_name="Endereço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro",
                "verbose_name_plural": "Membros",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Descrição"
                    ),
                ),
                ("number", models.CharField(max_length=15, verbose_name="Número")),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telefone",
                "verbose_name_plural": "Telefones",
            },
        ),
    ]
