# Generated by Django 6.0.3 on 2026-05-16 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(
                default=datetime.date(2026, 5, 16), verbose_name="Data de Entrada"
            ),
        ),
    ]
