# Generated by Django 6.0.3 on 2026-05-17 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_member_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(
                default=datetime.date(2026, 5, 17), verbose_name="Data de Entrada"
            ),
        ),
    ]
