# Generated by Django 6.0.3 on 2026-05-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carmel", "0001_initial"),
        ("members", "0004_alter_member_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="carmel",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="carmel.carmel",
            ),
        ),
    ]
