# Generated by Django 6.0.3 on 2026-06-05 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_member_carmel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(
                default=datetime.date(2026, 6, 5), verbose_name="Data de Entrada"
            ),
        ),
    ]
