# Generated by Django 6.0.3 on 2026-06-11 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_member_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="members.address",
                verbose_name="Endereço",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(
                default=datetime.date(2026, 6, 11), verbose_name="Data de Entrada"
            ),
        ),
    ]
