# Generated by Django 6.0.3 on 2026-06-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_member_address_alter_member_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.address",
                verbose_name="Endereço",
            ),
        ),
    ]
