# Generated by Django 6.0.3 on 2026-06-13 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_alter_member_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(
                default=datetime.date(2026, 6, 13), verbose_name="Data de Entrada"
            ),
        ),
    ]
