# Generated by Django 6.0.3 on 2026-06-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_alter_member_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(verbose_name="Data de Entrada"),
        ),
    ]
