# Generated by Django 6.0.3 on 2026-06-20 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_alter_member_entry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
