# Generated by Django 6.0.3 on 2026-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_remove_member_address_address_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(max_length=10, verbose_name="CEP"),
        ),
    ]
