# Generated by Django 4.2.30 on 2026-07-09 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carmel", "0005_alter_carmel_id_alter_carmel_name"),
        ("members", "0013_alter_address_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="carmel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="carmel.carmel",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="church",
            field=models.CharField(
                default="", max_length=100, verbose_name="Igreja que Participa"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Entrada"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
