# Generated by Django 4.2.30 on 2026-07-13 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0015_alter_address_id_alter_member_id_alter_phone_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="entry_date",
            field=models.DateField(verbose_name="Data de Entrada"),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nome do Membro"
            ),
        ),
    ]
