# Generated by Django 4.2.30 on 2026-07-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_alter_member_email_alter_member_entry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="church",
            field=models.CharField(max_length=100, verbose_name="Igreja que Participa"),
        ),
        migrations.AlterField(
            model_name="phone",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
