# Generated by Django 4.2.30 on 2026-07-28 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0017_alter_address_member_alter_member_church_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
